services:
  server:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    image: embed-server:dev

  sync-runner:
    build:
      context: .
      dockerfile: ./packages/sync-runner/Dockerfile
    image: embed-sync-runner:dev

  action-runner:
    build:
      context: .
      dockerfile: ./packages/action-runner/Dockerfile
    image: embed-action-runner:dev
