name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - 'feature/*'
      - 'release/*'
      - 'hotfix/*'
      - 'customer/*'
    paths:
      - 'packages/server/**'
      - 'packages/sync-runner/**'
      - 'packages/action-runner/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service:
          - name: server
            path: packages/server
            image: embed-server
          - name: sync-runner
            path: packages/sync-runner
            image: embed-sync-runner
          - name: action-runner
            path: packages/action-runner
            image: embed-action-runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract branch name
        id: extract_branch
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV

      - name: Build and push Docker image for ${{ matrix.service.name }}
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./${{ matrix.service.path }}/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.image }}:${{ env.BRANCH_NAME }}

      - name: Notify success
        if: success()
        run: echo "Successfully built and pushed ${{ matrix.service.name }} for branch ${{ env.BRANCH_NAME }}"
